services:
  traceops_db:
    image: postgres:16
    environment:
      POSTGRES_DB: traceops
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1992
    ports:
      - "5433:5432"
    volumes:
      - traceops_pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ConnectionStrings__Default: Host=traceops_db;Port=5432;Database=traceops;Username=postgres;Password=1992
      Automation__EventWebhookUrl: https://n8n-swg4ook08okkw0kgss8cc080.157.173.102.16.sslip.io/webhook/traceops-event
      Automation__InboundSecret: YOUR_LONG_RANDOM_SECRET
    depends_on:
      - traceops_db
    ports:
      - "8080:8080"

volumes:
  traceops_pgdata:
